blogTitle = "Chris Alexander"
subTitle = "A Londoner Learning JavaScript"
# blogUrl = "https://chrisalexander.me.uk"
authorName = "Chris Alexander"
# authorTwitter = "@ShutoTakahiro"
authorBio = "Written by <strong>Chris Alexander</strong>"
linkPrefix = "/"
gaCode = "UA-36311374-1"
# kommentsCode = ""
