blogTitle = "Chris Alexander"
subTitle = "A Londoner Learning JavaScript"
# blogUrl = "https://chrisalexander.me.uk"
authorName = "Chris Alexander"
# authorTwitter = "@ShutoTakahiro"
linkPrefix = "/"
gaCode = "UA-36311374-1"
# kommentsCode = ""
