backend:
  name: github
  repo: chris-alexander/chrisalexander.me.uk
  branch: master
  site_domain: chrisalexander.me.uk

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: blog-post }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Publish Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list, required: false }
